### PR TITLE
add v0.13.0-beta release

### PR DESCRIPTION
**Pull request by calvinrzachman**
Hi guys, 

This is a helpful repository. Got amped by the 0.13 release and was looking to create new images. 

Let me know if this looks good or if I should close in favor of a PR from you guys. 

Thanks!

### CODE REVIEW

**Comment by nolim1t** [comment]
Thanks for the pull request will take a look and merge

**Comment by nolim1t** [comment]
This will be available on dockerhub as soon as this script is ready

https://github.com/lncm/docker-lnd/actions/runs/948713231

**Comment by nolim1t** [comment]
Released and should be available on docker hub

https://github.com/lncm/docker-lnd/releases/tag/v0.13.0%2Bbuild1

**Comment by calvinrzachman** [comment]
@nolim1t awesome. Just pulled `v0.13.0` and it looks good so far. I don't see the image for the `etcd` patch up yet. Any ideas on how to get that one pushed? Do I need to use `create-variant.sh`?

**Comment by nolim1t** [comment]
I'm building all the variants now..  just have to remember the process as its been a while

**Comment by nolim1t** [comment]
Variants should be up there. Let me know if there are any issues

**Comment by calvinrzachman** [comment]
Can't say about all of them, but the etcd variant is looking good. Pretty cool to see the clustered lnd deployment support. Thanks for helping get these images up!

**Comment by nolim1t** [comment]
Thanks I'll merge this for documentation purposes then, also running two different types of lnd (stock and `experimental` tag variant)

We can safely ignore those past version build errors as they are expired PGP key issues

**Pull request merged**
