### PR TITLE
Correct entrypoint for lnd v0.10.0-beta

### PR DESCRIPTION
**Pull request by mayankchhabra**
It works 🤷‍♂️

Tested on macOS x64:

image

### CODE REVIEW

**Comment by nolim1t** [comment]
Seems the arm stuff is failing so we need @meeDamian to help fix this

**Comment by meeDamian** [comment]
Yes, `/bin/lnd` is definitely not correct.  But please change it to `/usr/local/bin/lnd` instead

**Comment by meeDamian** [comment]
Actually no. All other versions still use naked `lnd`, probably best to have a separate issue for that.

But I'm gonna push updated variants here before merge.

**Comment by mayankchhabra** [comment]
> All other versions still use naked `lnd`
Yeah, that's where I picked it from. Just updated with full-path and tested locally, works as expected.

**Comment by meeDamian** [comment]
Ha! You're too fast :P

**Comment by meeDamian** [comment]
Thank you, @mayankchhabra 🙌🏻.

**Pull request merged**
