### PR TITLE
Include 0.6 LND into docker

### PR DESCRIPTION
**Pull request by nolim1t**
Full Release notes [here](https://blog.lightning.engineering/announcement/2019/04/16/lnd-v0.6.html)

I've built this on AMD64 (Ubuntu)

### CODE REVIEW

**Comment by nolim1t** [comment]
Pushed another fix to make it build 0.6

**Comment by AnotherDroog** [comment]
How’s ARM looking?

**Comment by nolim1t** [comment]
To use the new 0.6 release ahead of the master release add ```lncm/lnd:0.6-linux-arm``` into your docker-compose file or do ```docker pull lncm/lnd:0.6-linux-arm```

**Comment by meeDamian** [comment]
Sorry, I just saw that now. 

All 0.6.0 images are now built and pushed to Docker Hub and Github releases. 

I've also updated automatic deployment process so no changes to travis files are necessary on subsequent releases, and added `git tag` signature verification in Docker before build.

Closing, as it's obsolete now…

**Pull request closed without merging**
